name:                hxx
version:             0.1.0.0
github:              "isqnwtn/hxx"
license:             BSD3
author:              "Vismay"
maintainer:          "vismayraj1@gmail.com"
copyright:           "2023 Vismay"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/isqnwtn/hxx#readme>

dependencies:
- base >= 4.7 && < 5
- optparse-applicative
- monomer
- data-default
- vector
- OpenGLRaw
- containers
- lens
- text
- text-show
- massiv
- hmatrix
- MonadRandom
- singletons
- singletons-base

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  hxx-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hxx

tests:
  hxx-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hxx
